### ISSUE TITLE
Transformer behavior when `model_missing_values=False`

### ISSUE THREAD

**Issue by npatki** [sdv-dev/RDT#414] opened 2022-03-01 22:23 UTC
### Problem Description

As described in #413: When `model_missing_values=False`, the reverse transform will attempt to assign missing values based on the number. This is not only unexpected, but is not guaranteed to be correct.

### Expected behavior

When `model_missing_values=False`:
- (Fit) Note down the % of values that are missing
- (Forward transform) No changes
- (Reverse transform) Randomly assign missing values so that the % of missing values is the same as what was observed during `fit`.

Notes:
1. We should aim to make the overall % missing the same. If the data already has some missing values, we should factor that in and only add more missing values if it gets us the desired %
2. We should fix a seed so that randomly assigning missing values happens the same way for the same input

**Example**: Assume 30% of the values in my datetime column are missing.
```python
ute = UnixTimestampEncoder(model_missing_values=False, missing_value_replacement="mean")

# this data is imputed with no missing values
transformed_data = ute.fit_transform(data)

# this data will have 30% missing values
reversed_data = ute.reverse_transform(transformed_data)

# there is a fixed seed so this this data will be the same as before
# that is: reversed_data = reversed_data_2
reversed_data_2 = ute.reverse_transform(transformed_data)

# assume this new dataset has 10% missing values
# then we'd add only 20% more missing values to get a total of 30% missing values in reversed_data_3
reversed_data_3 = ute.reverse_transform(new_data)
```

**Comment by amontanez24** [comment] 2022-03-24 19:20
Duplicate of #435 
Defer to #435 for the expected functionality

**Closed by amontanez24** 2022-03-24 19:20 UTC
Labels: new feature
